### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by name01019** [stck-lzm/badown#1]
Thanks for writing this program. Script stopped working recently for Zippyshare.

Output below:
./badown: line 129:
0, 3);
'dlbutton').omg.length;
Math.pow + 11: syntax error in expression (error token is ");
'dlbutton').omg.length;
Math.pow + 11")
mv: cannot move '.tmp' to '': No such file or directory./badown: line 129:
0, 3);
'dlbutton').omg.length;
Math.pow + 11: syntax error in expression (error token is ");
'dlbutton').omg.length;
Math.pow + 11")
mv: cannot move '.tmp' to '': No such file or directory

**Comment by stck-lzm** [comment]
I see where the problem is.
The zippyshare links are quite easy get.
There is a javascript in the download page that does some arithmetic to "protect" the download links.
They might have change the math.

**Comment by stck-lzm** [comment]
just pushed the new version, this should work now.
they indeed modified the arithmetic.
