### ISSUE TITLE
Handle missing Zippyshare files?

### ISSUE THREAD

**Issue by outhud** [stck-lzm/badown#3]
Tried badown for the first time today, there's an error from Zippyshare. Maybe they changed the layout?

> ./badown http://www15.zippyshare.com/v/SJRKbQv7/file.html
> (standard_in) 1: syntax error
> ./badown: line 133: %: syntax error: operand expected (error token is "%")

**Comment by outhud** [comment]
Just noticed this file was removed. I assume these are not handled in the script?

**Comment by stck-lzm** [comment]
Hello, just noticed your issue, I have a look at it and come back with a solution by friday hopefully.
It is not the first time this happen

**Comment by stck-lzm** [comment]
https://github.com/stck-lzm/badown/commit/75ce25f240ae448edd98c8743ab7dd18cd937c90 just pushed this, it should fix your problem.
