### ISSUE TITLE
badown gives exit 1 even if download operation is successful

### ISSUE THREAD

**Issue by rokibhasansagar** [stck-lzm/badown#6]
This line is giving out `exit 1` in function `file_down` even if everything is okay. This line is useless as temp file is moved as orig file, so how can anyone remove the temp file afterwards! You better delete this line: https://github.com/stck-lzm/badown/blob/7ad4407be7cc2076ed0b8f9e55338ca3e7219327/badown#L78

Also, This line explicitly tells to `exit 1` after download tasks, which eventually gives `exit 1` even if upper line is removed: https://github.com/stck-lzm/badown/blob/7ad4407be7cc2076ed0b8f9e55338ca3e7219327/badown#L197

Both lines when removed and tested with mediafire as-well-as mega links with bash trace enabled, and I get no `exit 1` anywhere.
Couldn't test zippyshare as their algorithm is changed (yet easy to fix)

**Comment by stck-lzm** [comment]
Hello,

Thank you for taking time to read script, You are right, `exit 1` is just for general error, It should return `exit 0` instead.
I will push the new version with fixed zippyshare

**Comment by stck-lzm** [comment]
done f15a3019
