### ISSUE TITLE
Hey I get this error when I try to download 

### ISSUE THREAD

**Issue by jelliedpizza** [stck-lzm/badown#7]
awk: line 1: regular expression compile failed (missing operand)

**Comment by jelliedpizza** [comment]
I found the issue but I didn't really delve into it too deep. I have a different version of awk (there are 3 for some reason), and in my version, the old one, regexp characters have to be escaped with a backslash.
So
```
file_name=$(printf '%b' "$(echo $file_url \
      | awk -F'/' '{gsub("%","\\x");gsub("+"," ");print $NF}')")
                                          ^
```
should be
```
file_name=$(printf '%b' "$(echo $file_url \
      | awk -F'/' '{gsub("%","\\x");gsub("\+"," ");print $NF}')")
                                          ^
```

**Comment by pitsi** [comment]
Almost 5 years later, I want to thank you for mentioning the needed change.
If anyone else comes accross it, the part that has to be changed is now on line 166.
